name: Setup Rust Environment
description: Sets up Rust toolchain with caching for io_uring_sync4 project
branding:
  icon: package
  color: orange

inputs:
  toolchain:
    description: Rust toolchain version
    required: false
    default: '1.90.0'
  components:
    description: Additional components to install
    required: false
    default: 'rustfmt, clippy'

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
    
    - name: Cache Rust dependencies and build artifacts
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v1-io-uring-sync"
        shared-key: "${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}"
        cache-all-crates: "true"
        cache-workspace-crates: "true"
        cache-bin: "true"
        save-if: ${{ github.ref == 'refs/heads/main' }}

