# Minimal clippy configuration for settings that cannot be in Cargo.toml
# Main lint configuration is now in Cargo.toml [workspace.lints.clippy]

# Documentation linting
doc-valid-idents = ["self", "Self", "super", "crate", "Self", "T", "E", "Ok", "Err"]

# Performance and correctness
disallowed-names = ["foo", "bar", "baz", "tmp", "temp"]
# Note: HashMap and BTreeMap are allowed. Use DashMap for concurrent access when needed.
disallowed-types = []
disallowed-methods = ["std::panic::panic_any"]

# Complexity thresholds (also configured in Cargo.toml for lint levels)
too-many-arguments-threshold = 5
too-many-lines-threshold = 100
single-char-binding-names-threshold = 2

# Test code policy: allow unwrap/expect in tests
allow-unwrap-in-tests = true
allow-expect-in-tests = true

