repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-docstring-first
      - id: check-case-conflict

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-rustfmt
    rev: v1.5.1
    hooks:
      - id: rustfmt
        args: [--edition, "2021", --all]

    - repo: https://github.com/pre-commit/mirrors-clippy
      rev: v1.75
    hooks:
      - id: clippy
        args: [--all-targets, --all-features, --, -D, warnings, -D, clippy::missing_docs_in_crate_items, -D, clippy::missing_errors_doc, -D, clippy::missing_panics_doc, -D, clippy::must_use_candidate]

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.75
    hooks:
      - id: fmt
      - id: clippy
        args: [--all-targets, --all-features, --, -D, warnings, -D, clippy::missing_docs_in_crate_items, -D, clippy::missing_errors_doc, -D, clippy::missing_panics_doc]
      - id: cargo-check
      - id: cargo-test
        args: [--all-features]
      - id: cargo-doc
        args: [--document-private-items, --no-deps]

  # Security and dependency checking
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
