repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-docstring-first
      - id: check-case-conflict

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3

  # Rust formatting and linting for workspace
  - repo: https://github.com/pre-commit/mirrors-rustfmt
    rev: v1.5.1
    hooks:
      - id: rustfmt
        args: [--edition, "2021", --all]
        # Run on all Rust files in workspace including tests
        files: ^(src/|crates/.*/src/|tests/).*\.rs$

  - repo: https://github.com/pre-commit/mirrors-clippy
    rev: v0.1.67
    hooks:
      - id: clippy
        args: [--workspace, --all-targets, --all-features, --no-deps, --, -D, warnings, -D, clippy::missing_docs_in_crate_items, -D, clippy::missing_errors_doc, -D, clippy::missing_panics_doc, -D, clippy::must_use_candidate]
        # Run on all Rust files in workspace including tests (--no-deps for speed)
        files: ^(src/|crates/.*/src/|tests/).*\.rs$

  # Comprehensive Rust quality checks for workspace
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
        args: [--workspace, --all-targets, --all-features]
      - id: cargo-test
        args: [--workspace, --all-features]
      - id: cargo-doc
        args: [--workspace, --document-private-items, --no-deps]

  # Security and dependency checking
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
