# Clippy configuration for strict code quality enforcement
# This enforces high documentation and code quality standards

# Documentation linting
doc-valid-idents = ["self", "Self", "super", "crate", "Self", "T", "E", "Ok", "Err"]
doc-link-with-http = true

# Performance and correctness
disallowed-names = ["foo", "bar", "baz", "tmp", "temp"]
disallowed-types = ["std::collections::HashMap", "std::collections::BTreeMap"]
disallowed-methods = ["unwrap", "expect", "panic"]

# Complexity limits
too-many-arguments-threshold = 5
too-many-lines-threshold = 100
single-char-lifetime-names = false
