# Clippy configuration for strict code quality enforcement
# This enforces high documentation and code quality standards

# Documentation linting
doc-valid-idents = ["self", "Self", "super", "crate", "Self", "T", "E", "Ok", "Err"]

# Performance and correctness
disallowed-names = ["foo", "bar", "baz", "tmp", "temp"]
disallowed-types = ["std::collections::HashMap", "std::collections::BTreeMap"]
disallowed-methods = ["std::panic::panic_any"]

# Complexity limits
too-many-arguments-threshold = 5
too-many-lines-threshold = 100
single-char-binding-names-threshold = 2
