# Clippy configuration for strict code quality enforcement
# This enforces high documentation and code quality standards

# Documentation linting
doc-valid-idents = ["self", "Self", "super", "crate", "Self", "T", "E", "Ok", "Err"]

# Performance and correctness
disallowed-names = ["foo", "bar", "baz", "tmp", "temp"]
# Explicitly NOT disallowing HashMap/BTreeMap - they are fine to use when appropriate.
# Previous rule required #[allow(clippy::disallowed_types)] everywhere, which is
# unnecessarily verbose and doesn't provide real value. Use the right data structure
# for your use case without artificial restrictions.
# disallowed-types = ["std::collections::HashMap", "std::collections::BTreeMap"]
disallowed-methods = ["std::panic::panic_any"]

# Complexity limits
too-many-arguments-threshold = 5
too-many-lines-threshold = 100
single-char-binding-names-threshold = 2

# Test code policy: allow unwrap/expect in tests
allow-unwrap-in-tests = true
allow-expect-in-tests = true

# Note: Enabling pedantic/nursery is done via CLI flags in CI and pre-commit.
