# Cargo-deny configuration for comprehensive code quality enforcement
# This file enforces strict standards for dependencies, licensing, and security

[advisories]
# Ignore specific advisories that are false positives or acceptable risks
ignore = [
    "RUSTSEC-2021-0119",  # nix - vulnerability in iou dependency, getgrouplist not used in our code
    "RUSTSEC-2024-0436",  # paste - dunno what to do yet
    "RUSTSEC-2025-0021",  # gitoxide - it uses SHA1
]
# Check for unmaintained crates
#unmaintained = "allow"
# Check for yanked crates
yanked = "deny"

[licenses]
# Allow specific licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "Zlib",
]


[sources]
# Allow specific registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# Deny unknown sources
unknown-registry = "deny"
# Allow specific git sources
allow-git = []


[bans]
multiple-versions = "allow"
# Check for multiple versions of the same crate
# Allow specific wildcard dependencies
wildcards = "deny"

