# Cargo-deny configuration for comprehensive code quality enforcement
# This file enforces strict standards for dependencies, licensing, and security

[advisories]
# Ignore specific advisories that are false positives or acceptable risks
ignore = [
    "RUSTSEC-2024-0436",  # paste - dunno what to do yet
]
# Check for unmaintained crates
#unmaintained = "allow"
# Check for yanked crates
yanked = "deny"

[licenses]
# Allow specific licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",  # Used by arrayref (dependency of blake3)
    "BSD-3-Clause",  # Common BSD license
    "0BSD",          # Zero-clause BSD (used by adler crate)
    "Unicode-3.0",
    "Zlib",
]

[sources]
# Allow specific registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# Deny unknown sources
unknown-registry = "deny"
# Allow specific git sources
allow-git = []

[bans]
multiple-versions = "allow"
# Check for multiple versions of the same crate
# Allow wildcard dependencies for internal workspace crates
wildcards = "allow"