[tasks.syscall-analysis]
description = "Run syscall analysis on arsync"
dependencies = ["build-release"]
script = '''
#!/bin/bash
echo "Running syscall analysis..."
./benchmarks/syscall_analysis.sh /tmp/arsync-test-src /tmp/arsync-test-dst 5 10
'''

[tasks.build-release]
description = "Build arsync in release mode"
command = "cargo"
args = ["build", "--release"]
