name: CI

on:
  push:
    branches: [ main, develop, phase-3-1-statx-xattr ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache Rust dependencies and build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "io-uring-sync"
          cache-all-crates: "true"
          cache-workspace-crates: "true"
          cache-bin: "true"

      - name: Install cargo-make
        run: cargo install cargo-make --locked

      - name: Lint (cargo-make)
        run: cargo make lint

      - name: Test (cargo-make)
        run: cargo make test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
        with:
          toolchain: stable

      - name: Cache Rust dependencies and build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "io-uring-sync"
          cache-all-crates: "true"
          cache-workspace-crates: "true"
          cache-bin: "true"

      - name: Install cargo-make
        run: cargo install cargo-make --locked

      - name: Run coverage (colored, skip #[ignore]) via cargo-make
        env:
          CARGO_TERM_COLOR: always
        run: cargo make coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage
